# usage: parse.py FILE

import sys
from antlr4 import *

# generated by antlr:
from PyLexer import PyLexer
from PyParser import PyParser

if len(sys.argv) != 2:
    print("usage: parse.py FILE")
    sys.exit(1)

fp = sys.argv[1]
with open(fp, "r") as f:
    s = f.read()

ins = InputStream(s)
lexer = PyLexer(ins)
stream = CommonTokenStream(lexer)
parser = PyParser(stream)
tree = parser.program()

errors = parser.getNumberOfSyntaxErrors()
if errors > 0:
    print(f"{errors} syntax errors")
    sys.exit(1)

print(tree.toStringTree(recog=parser))
