# usage: parse.py PYTHON_FILE

import sys
from antlr4 import *

# generated by antlr:
from PyLexer import PyLexer
from PyParser import PyParser

from preprocessor import preprocess

def main():
    if len(sys.argv) != 2:
        print("usage: parse.py PYTHON_FILE")
        sys.exit(1)

    fp = sys.argv[1]

    with open(fp, "r") as f:
        script = f.read()
    p_script = preprocess(script)

    ins = InputStream(p_script)
    lexer = PyLexer(ins)
    stream = CommonTokenStream(lexer)
    parser = PyParser(stream)
    tree = parser.program()

    errors = parser.getNumberOfSyntaxErrors()
    if errors > 0:
        print(f"{errors} syntax errors")
        sys.exit(1)

    print(tree.toStringTree(recog=parser).replace("\\n", "\n"))

if __name__ == "__main__":
    main()
